name: "Staging: Deploy CloudFront + Lambda@Edge SAM Stack"
on: 
  push:
    branches:
    - staging

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - run: python -m pip install --upgrade pip
    - run: pip install 'aws-sam-cli==1.11.0'
    - run: sam validate
    - run: sam build
    - run: "sam deploy \
      --stack-name ${AWS_STACK_NAME} \
      --s3-prefix ${AWS_BUCKET_PREFIX} \
      --s3-bucket ${AWS_DEPLOY_BUCKET} \
      --capabilities CAPABILITY_IAM \
      --no-fail-on-empty-changeset \
      --parameter-overrides \"${PARAMETER_OVERRIDES}\"" 
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_BUCKET_PREFIX: "aws-sam-cli-managed-default-samclisourcebucket-testing-12345678"
      AWS_DEPLOY_BUCKET: "cascade-aip-marcom-tamu-edu-edge-rewrite"
      AWS_DEFAULT_REGION: 'us-east-1'
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_STACK_NAME: "cascade-aip-marcom-tamu-edu-edge-rewrite"
      SAM_CLI_TELEMETRY: 0
      TEMPLATE: 'template.yaml'
      PARAMETER_OVERRIDES: >-
        ParameterKey=Alias,ParameterValue=marcomm-website-example-staging.aws.cloud.tamu.edu 
        ParameterKey=BucketName,ParameterValue=marcomm-website-example-staging.aws.cloud.tamu.edu 
        ParameterKey=CertARN,ParameterValue=arn:aws:acm:us-east-1:449349294279:certificate/0aaea236-4b20-413e-bdcd-60a2cfe657ab
        ParameterKey=DefaultTTL,ParameterValue=60 
        ParameterKey=Description,ParameterValue=MarComm-website-example 
        ParameterKey=MaxTTL,ParameterValue=60 
        ParameterKey=LoggingBucketName,ParameterValue=marcomm-website-example-staging-logs.aws.cloud.tamu.edu 
        ParameterKey=RulesURL,ParameterValue=https://raw.githubusercontent.com/aggie-innovation-platform-private/aws-tamu-lambda-redirect-rules-main/staging/rules/rules.json?token=ABA6AIJAZ5K5IVI7XLXQMJ27Y65UI
